---
 - name: clear the tmp file
   shell: rm -rf listsubnetid.lst

 - name: populate subnet ids from subnet tags
   shell: automation-scripts/findSubnetid.sh "{{ nfsserver_subnet_id }}" "{{ region_name }}"

 - name: set the subnet ids in a variable
   shell: echo "{{ item }}"
   with_lines:
   -  cat listsubnetid.lst
   register: vpc_subnet_ids

 - name: nfs server instance provisioning
   local_action:
     module: ec2
     assign_public_ip: yes
     region: "{{ region_name }}"
     key_name: "{{ sshkeynameinaws }}"
     instance_type: "{{ nfsserver_instance_type}}"
     image: "{{ nfsserver_ami_image }}"
     group: "{{ securitygroup_prefix }}_{{nfsserver_prefix}}"
     instance_profile_name: "{{nfs_role_name}}"
     instance_tags:
           Name: "{{ prefix }}_nfsserver"
           class: nfsserver
           environment: "{{ environment_prefix }}"
     id: "{{vm_instance_id}}_nfsserver"
     volumes:
       - device_name: /dev/xvda
         volume_type: gp2
         volume_size: 8
     vpc_subnet_id: "{{ item }}"
     user_data:  "{{ lookup('file','{{nfsserver_user_data_file}}') }}"
     wait: true
 #    security_token: "{{ aws_security_token }}"
   register: ec2
   with_lines:
   - cat listsubnetid.lst 

# - name: set facts..
#   set_fact: nfs_server_ip="{{item.private_dns_name}}"
#   with_items: ec2.results.instances
# - name: associate new EIP for the instance
#   local_action:
#     module: ec2_eip
#     region: "{{ region_name }}"
#     device_id: "{{ item.id }}"
#     security_token: "{{ aws_security_token }}"
#     state: present
#   with_items: ec2.instances
#   when: item.id is defined
