asg_min_size: 1
asg_max_size: 3
asg_desired_capacity: 1
#launch config
#lc_prefix: lc
#auto scaling group
#asg_prefix: asg
replace_all_instances_Yes: yes
replace_all_instances_No: no

autoscalinggroups:
  -
    asg_name: "{{prefix}}{{asg_prefix}}-1"
    health_check_period: 500
    lb_name: "{{prefix}}{{loadbalancer_prefix}}-1"
    health_check_type: ELB
    availability_zones:
      - us-west-1a
    launch_config_name: "{{prefix}}{{lc_prefix}}-1"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    replace_all_instances: "{{ replace_all_instances_Yes }}"
    vm_name_tag: "{{ prefix }}_{{ webserver_prefix }}"
    subnet_names: "{{prefix}}{{subnet_prefix}}-1^{{prefix}}{{subnet_prefix}}-2"

  -
    asg_name: "{{prefix}}{{asg_prefix}}-2"
    health_check_period: 500
    lb_name: "{{prefix}}{{loadbalancer_prefix}}-2"
    health_check_type: ELB
    availability_zones:
      - us-west-1a
    launch_config_name: "{{prefix}}{{lc_prefix}}-2"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_desired_capacity }}"
    replace_all_instances: "{{ replace_all_instances_Yes }}"
    vm_name_tag: "{{ prefix }}_{{ apiserver_prefix }}"
    subnet_names: "{{prefix}}{{subnet_prefix}}-1^{{prefix}}{{subnet_prefix}}-2" 
