#eIt s a listing of load balancer..
#facing: represent lb is internet facing or internal
loadbalancers:
  -
    lb_name: "{{prefix}}{{loadbalancer_prefix}}-1"
    facing_scheme: "{{ lb_internet_facing_scheme }}"
    cross_az_load_balancing: "{{ lb_cross_az_yes }}"
    lb_healthcheck: "{{ lb_healthcheck_tcp_22 }}"
    lb_listeners: "{{ lb_listeners_tcp_80 }}"
    securitygroup_names: "{{ securitygroup_prefix }}_{{loadbalancer_prefix}}"
    subnet_names: "{{prefix}}{{subnet_prefix}}-1^{{prefix}}{{subnet_prefix}}-2"
    zones: "{{all_zones}}"
  -
    lb_name: "{{prefix}}{{loadbalancer_prefix}}-2"
    facing_scheme: "{{ lb_internal_facing_scheme }}"
    cross_az_load_balancing: "{{ lb_cross_az_yes }}"
    lb_healthcheck: "{{ lb_healthcheck_tcp_22 }}"
    lb_listeners: "{{ lb_listeners_tcp_80 }}"
    securitygroup_names: "{{ securitygroup_prefix }}_{{loadbalancer_prefix}}"
    subnet_names: "{{prefix}}{{subnet_prefix}}-1^{{prefix}}{{subnet_prefix}}-2"
    zones: "{{all_zones}}"
