nat_instance_type: t1.micro
nat_ami_image: ami-67a54423
nat_subnet_id: "{{prefix}}{{subnet_prefix}}-1"
sec_nat_rules:
  - proto: tcp
    from_port: 22
    to_port: 22
    cidr_ip: "{{ allowed_all_ip }}"
  - proto: tcp
    from_port: 443
    to_port: 443
    cidr_ip: "{{ allowed_all_ip }}"
  - proto: tcp
    from_port: 943
    to_port: 943
    cidr_ip: "{{ allowed_all_ip }}"
  - proto: udp
    from_port: 1194
    to_port: 1194
    cidr_ip: "{{ allowed_all_ip }}"
