---
 - name: clear the tmp file
   shell: rm -rf listsubnetid.lst

 - name: populate subnet ids from subnet tags
   shell: automation-scripts/findSubnetid.sh "{{ openvpn_subnet_id }}" "{{ region_name }}"

 - name: set the subnet ids in a variable
   shell: echo "{{ item }}"
   with_lines:
   -  cat listsubnetid.lst
   register: vpc_subnet_ids

 - name: open vpn instance provisioning
   local_action:
     module: ec2
     assign_public_ip: yes
     region: "{{ region_name }}"
     key_name: "{{ sshkeynameinaws }}"
     instance_type: "{{ openvpn_instance_type}}"
     image: "{{ openvpn_ami_image }}"
     group: "{{ securitygroup_prefix }}_{{openvpn_prefix}}" 
     instance_tags:
           Name: "{{ prefix }}_openvpn"
           class: openvpn
           environment: "{{ environment_prefix }}"
     id: "{{vm_instance_id}}_openvpn"
     vpc_subnet_id: "{{ item }}"
     source_dest_check: no
     wait: yes
#     security_token: "{{ aws_security_token }}"
   register: ec2
   with_lines:
   - cat listsubnetid.lst 

# - name: associate new EIP for the instance
#   local_action:
#     module: ec2_eip
#     region: "{{ region_name }}"
#     device_id: "{{ item.id }}"
#     security_token: "{{ aws_security_token }}"
#     state: present
#   with_items: ec2.instances
#   when: item.id is defined
